# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)
print(np.show_config())

2.3.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5t0hy_xh/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5t0hy_xh/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5t0hy_xh/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5t0hy_xh/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuratio

#### 3. Create a null vector of size 10

In [3]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [4]:
a = arr.size
b = arr.itemsize
print("{} bytes".format(a*b))

80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [5]:
np.add?

Signature:       np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\users\siddh\appdata\roaming\python\python313\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [7]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [8]:
arr = np.arange(10,50,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45])

#### 8.  Reverse a vector (first element becomes last)

In [9]:
np.flipud(arr)

array([45, 40, 35, 30, 25, 20, 15, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
arr = np.random.randint(0,9,(3,3))
arr

array([[2, 3, 0],
       [3, 3, 3],
       [6, 4, 1]], dtype=int32)

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [15]:
arr = np.array([1,2,0,0,4,0])
ans = np.nonzero(arr)
ans

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix

In [16]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [18]:
np.random.random((3,3,3))

array([[[0.15202227, 0.91531398, 0.84973635],
        [0.58457127, 0.3392101 , 0.8743909 ],
        [0.47802115, 0.33564529, 0.24639846]],

       [[0.63904451, 0.46944696, 0.02463203],
        [0.51243817, 0.74436632, 0.21935116],
        [0.35568054, 0.92133233, 0.19548086]],

       [[0.12870424, 0.79770752, 0.89827627],
        [0.32870823, 0.41930703, 0.89103075],
        [0.13840917, 0.11796109, 0.82465543]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
arr = np.random.random((10,10,10))
a = np.max(arr)
b = np.min

#### 14. Create a random vector of size 30 and find the mean value

#### 15. Create a 2d array with 1 on the border and 0 inside

#### 16. How to add a border (filled with 0's) around an existing array?

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?